# sc-nfs.yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfsstorage-sc
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.8.95.84
  share: /data02/nfsstorage
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
allowVolumeExpansion: true